### ISSUE TITLE
Log4slime Error Upon Startup (org-compatible-face)

### ISSUE THREAD

**Issue by Shinmera** [7max/log4cl#15]
I installed log4cl and log4slime through Quicklisp and executed the install command.
After adding the requested lines to my .emacs file, I get the following error on Emacs launch:

```
Symbol's function definition is void: org-compatible-face
```

I'm usually running Emacs on my terminal, but even if I start it in X mode, the error still occurs. The Emacs version is 
`GNU Emacs 24.3.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.8.1) of 2013-04-29 on eric` 
and the log4slime version from Quicklisp is
`#<SYSTEM log4slime / log4cl-stable-26f358ee-git / quicklisp 2013-06-15>`

If there's any additional information on my setup that you need, I'd be happy to provide you with what I can.

**Comment by 7max** [comment]
Ok, this seems to be some bug / miscommunication with Xach.. He was supposed to switch QuickLisp to pull from stable branch, but this last updated pulled tip, and not stable branch..

Log4Slime is not even in the stable branch, it looks like QuickLisp now has rev 26f358ee from master.

The bug you reporting was a bug, but already fixed around 2 weeks ago in master, in the commit bb7f3fa51216937b103a43aba8d66e6486a530eb

You have two choices here, both involve making a local copy log4cl via ~/local-projects, as described in readme. You can checkout either "stable" branch if you don't want any disruption or "master" branch for latest.

I meanwhile will try to sort out this issue with Xach and decide what to do

**Comment by 7max** [comment]
This issue explains some rather strange bug reports. It seems correct decision here is to resume pulling QuickLisp from master branch, since otherwise would be just jerking people around.

**Comment by 7max** [comment]
Meanwhile opened https://github.com/quicklisp/quicklisp-projects/issues/524 as this issue may affect other projects then Log4CL, if some other projects also requested "pull from branch" from QuickLisp

**Comment by Shinmera** [comment]
Replacing the Quicklisp log4cl folder's contents with a clean pull fixed the issue.
Thanks a lot for the quick reply!

This could be closed from my initial problem's perspective, but I'll leave it open for now in relation to the Quicklisp bug.
Of course, you may close this if you see it fit.

**Comment by 7max** [comment]
It makes no sense to downgrade QuickLisp version now, so I've asked Xach to switch back to continue pulling "master" now instead.. Bumped version to 1.1.1 in preparation for next QuickLisp freeze, nad closing this issue.
