### ISSUE TITLE
Breakage due to ASDF package changes

### ISSUE THREAD

**Issue by fare** [7max/log4cl#5]
Recent versions of ASDF do not export GETENV or any utilities anymore.
This breaks log4cl.

The fix is to either
1- use ASDF-UTILS that exports all these utilities, or
2- use internal symbols like ASDF::GETENV if you really can't or won't depend on ASDF-UTILS.

Please test with a new ASDF (such as 2.25), without loading any system-provided ASDF via require.
My apologies for the breakage.

**Comment by 7max** [comment]
Fixed for now by using asdf::getenv, will do require asdf-utils in the devel branch, since I have bunch of new stuff there anyway.
